import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { deliverSignalToFormsubmit } from "@/lib/spiix-leads";
import { recordSignalSubmission } from "@/lib/spiix-leads.functions";
import { ArrowRight, ArrowUpRight, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FrameworkTable } from "@/components/spiix-frameworks";
import { signalRequestSchema, unlockMonolith } from "@/lib/spiix-access";
import { monolithChapters, monolithPreviews } from "@/data/spiix-monolith";
import { featuredRecommendations } from "@/data/resume";
import heroImage from "@/assets/spiix/spiix-hero.jpg";

export const Route=createFileRoute("/spiix/signal")({head:()=>({meta:[{title:"Get the Signal — The Growth Decision Framework | SPIIX"},{name:"description",content:"Get the Signal is the growth decision framework. Signal is the measure; the SPIIX OS puts the framework to work; Monolith holds the complete body of work."},{property:"og:title",content:"Get the Signal — SPIIX"},{property:"og:description",content:"Signal is the measure. Get the Signal is the framework. The OS puts it to work. Monolith holds the whole."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"https://stevepeeleii.com/spiix/signal"}]}),component:SignalPage});

function SignalPage(){
  const navigate=useNavigate();const record=useServerFn(recordSignalSubmission);const [data,setData]=useState({name:"",email:"",company:"",role:""});const [errors,setErrors]=useState<Record<string,string>>({});const [storageError,setStorageError]=useState("");
  return <main className="sx-signal-page"><section className="sx-signal-hero"><img src={heroImage} alt="Monolithic concrete tower"/><div className="sx-hero-grid"/><div className="spiix-wrap"><p className="spiix-kicker sx-rise-1">SPIIX / GET THE SIGNAL / THE FRAMEWORK</p><div className="sx-signal-mark sx-mark-stage"><span className="sx-mark-reveal">SPIIX</span><span className="spiix-kicker">STRATEGIC<br/>OPERATING SYSTEM</span></div><h1 className="sx-mark-reveal">Get the<br/><span>Signal.</span></h1><p className="sx-signal-promise sx-rise-2">Signal is the measure.<br/>Get the Signal is how you read it and decide.</p><p className="sx-section-narrative sx-rise-3">A framework for founders and growth leaders: define the measure, read the constraint, choose the intervention, and check the result. The SPIIX OS gives those choices owners, workflows, and a review cadence. Monolith brings the whole body of work together.</p><div className="sx-actions sx-rise-4"><Button asChild className="spiix-button"><a href="#signal-access">GET THE SIGNAL <ArrowRight/></a></Button><a href="#inside" className="spiix-text-link">The framework & the whole <ArrowUpRight/></a></div><div className="sx-signal-spec sx-rise-5"><span>08 CHAPTERS</span><span>WORKED EXAMPLES</span><span>ILLUSTRATED FRAMEWORKS</span><span>PDF INCLUDED</span></div></div></section>
  <section className="spiix-section sx-signal-proof"><div className="spiix-wrap"><p className="spiix-kicker">BUILT FROM OPERATING EXPERIENCE / NOT BORROWED CERTAINTY</p><div className="sx-mini-stats">{[["14+","Years across SaaS, startups & technology"],["$350M+","Annual pipeline exposure at NTT DATA/Nexient"],["5+","Regions across global marketing integration"],["4","Acquisition-related outcomes"]].map(([value,label])=><div key={value}><strong>{value}</strong><span>{label}</span></div>)}</div></div></section>
  <section id="inside" className="spiix-section"><div className="spiix-wrap"><p className="sx-section-label"><span>01</span><i/>THE FRAMEWORK / THE MECHANISM / THE WHOLE</p><h2 className="sx-heading">Different names. Different jobs.</h2><p className="sx-section-narrative">Get the Signal is not another name for Monolith. It is the framework within it. The OS is how that framework becomes repeatable work.</p><FrameworkTable caption="THE WORK / FOUR CLEAR DEFINITIONS" headings={["Name","Meaning"]} rows={[["Signal","A defined measure: what is counted, for which cohort, in what unit and window, and which decision it informs."],["Get the Signal","The framework: define, observe, locate, decide, act, and read back."],["The OS","The mechanism: owners, decision rights, workflows, tools, and review cadence that put the framework to work."],["Growth Ladders Monolith / Monolith","The entirety: the framework, operating system, Growth Ladders, playbooks, instruments, and principles."]]}/><h3 className="sx-document-subhead">Inside the SPIIX operating guide.</h3><p className="sx-section-narrative">Eight connected chapters within Monolith. Growth Ladders — Operators Edition is the companion book, with its own playbooks and diagnostic.</p><div className="sx-actions"><Link to="/growth-ladders" className="spiix-text-link">Explore Growth Ladders <ArrowUpRight/></Link></div><div className="sx-chapter-preview">{monolithChapters.map((chapter,i)=><article key={chapter}><span>0{i+1}</span><div><h3>{chapter}</h3><p>{monolithPreviews[i]}</p></div><ArrowUpRight/></article>)}</div></div></section>
  <section className="spiix-section"><div className="spiix-wrap"><p className="sx-section-label"><span>02</span><i> </i>THE OPERATOR / WHAT LEADERS SAY</p><div className="sx-testimonial-grid">{featuredRecommendations.slice(0,3).map(item=><article key={item.name}><span className="sx-quote-mark">“</span><blockquote>{item.quote}</blockquote><h3>{item.name}</h3><p>{item.title}</p></article>)}</div></div></section>
  <section id="signal-access" className="spiix-section"><div className="spiix-wrap sx-gate-layout"><div><p className="sx-section-label"><span>03</span><i/>GET THE SIGNAL / INSTANT ACCESS</p><h2 className="sx-heading">Use the framework.<br/>Open the Monolith.</h2><p className="sx-section-narrative">Start with Get the Signal, see how the OS puts it to work, and read the SPIIX operating guide within Monolith. Use the live instruments and download that guide. Growth Ladders has its own book and reading path.</p><div className="sx-document-stamp"><FileText/><span>MONOLITH / SPIIX OPERATING GUIDE<br/>STEVE PEELE II / SPIIX</span></div></div><form className="sx-intake-panel sx-clip" noValidate onSubmit={event=>{event.preventDefault();const parsed=signalRequestSchema.safeParse(data);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(issue=>[String(issue.path[0]),issue.message])));return;}setErrors({});const submission={...parsed.data,id:crypto.randomUUID(),pageUrl:window.location.href,pageName:document.title};void deliverSignalToFormsubmit(submission);void record({data:submission}).then(result=>{if(!result.stored)void record({data:submission}).catch(()=>{});}).catch(()=>{void record({data:submission}).catch(()=>{});});if(!unlockMonolith()){setStorageError("Allow browser storage to save your access, then try again.");return;}void navigate({to:"/spiix/monolith"});}}><p className="spiix-kicker">YOUR CONTEXT / FOUR DETAILS</p><div className="sx-intake-fields">{(["name","email","company","role"] as const).map(key=><div className="spiix-field" key={key}><label htmlFor={`signal-${key}`}>{key}</label><input id={`signal-${key}`} value={data[key]} type={key==="email"?"email":"text"} autoComplete={key==="email"?"email":key==="name"?"name":key==="company"?"organization":"organization-title"} required maxLength={key==="email"?254:key==="company"?120:100} aria-invalid={Boolean(errors[key])} aria-describedby={errors[key]?`signal-error-${key}`:undefined} onChange={e=>setData({...data,[key]:e.target.value})}/>{errors[key]&&<p id={`signal-error-${key}`} className="sx-intake-error">{errors[key]}</p>}</div>)}</div>{Object.keys(errors).length>0&&<p role="alert" className="sx-intake-error">Complete the four details to open the guide.</p>}{storageError&&<p role="alert" className="sx-intake-error">{storageError}</p>}<Button type="submit" className="spiix-button">GET THE SIGNAL <ArrowRight/></Button><p className="sx-footnote">Access is saved on this browser only. Your details are sent through FormSubmit for email delivery to Steve and recorded for follow-up. This is a local access step, not a private document vault.</p><Link to="/spiix/connect" className="spiix-text-link">Start a conversation instead →</Link></form></div></section>
  <section className="spiix-section"><div className="spiix-wrap sx-signal-faq"><div><p className="sx-section-label"><span>04</span><i/>BEFORE YOU OPEN IT</p><h2 className="sx-heading">Clear expectations.</h2></div><div>{[["Who is this for?","Founders, growth leaders, and operators who need commercial decisions to connect to execution. The frameworks apply across motions; the right intervention depends on your context."],["Is this a course or a sales deck?","Neither. Get the Signal is a decision framework. The OS puts it into operation. Monolith contains the full body of work; this access step opens its SPIIX operating guide. Engagement models are covered, with no obligation to engage."],["Do the models predict my results?","No. Every worked example is hypothetical. Instruments label the baseline, units, and assumptions. Use them to pressure-test a decision, then validate it with your own cohorts and economics."],["What happens to my details?","Your name, email, company, and role are sent through FormSubmit for email delivery to Steve and recorded for follow-up. Reading access is instant, even if delivery is delayed. Only the access flag is saved in your browser."],["Can I keep a copy?","Yes. Once inside, download the SPIIX operating guide PDF with the current instrument readings. A print-ready version is also available. Access on another browser requires this short step again."]].map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
  <section className="spiix-section"><div className="spiix-wrap sx-direct-line"><p className="spiix-kicker">THE NEXT DECISION / START HERE</p><h2>Activity is easy.<br/>Useful output isn’t.</h2><div className="sx-actions"><Button asChild className="spiix-button"><a href="#signal-access">GET THE SIGNAL <ArrowRight/></a></Button><Link to="/spiix" className="spiix-text-link">← Back to SPIIX</Link></div></div></section></main>;
}