import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowUpRight, Download, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { hasMonolithAccess } from "@/lib/spiix-access";
import { OsDeepDive, BlueprintDeepDive, SignalDeepDive, OperatorPrinciples, FrameworkTable } from "@/components/spiix-frameworks";
import { VelocityModeler, ImpactEngine } from "@/components/spiix-impact-tools";
import { MonolithDepth } from "@/components/spiix-monolith-depth";
import { monolithChapters } from "@/data/spiix-monolith";
import { glossary } from "@/data/spiix-frameworks";

export const Route=createFileRoute("/spiix/monolith")({head:()=>({meta:[{title:"Monolith — The SPIIX Operating Guide"},{name:"description",content:"The SPIIX operating guide within Growth Ladders Monolith: Get the Signal, its operating system, pipeline instruments, and principles."},{property:"og:title",content:"The Monolith — SPIIX"},{property:"og:description",content:"Monolith is the entirety. Read the SPIIX operating guide: the framework, its mechanism, and the instruments."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary"},{name:"robots",content:"noindex, nofollow"}],links:[{rel:"canonical",href:"https://stevepeeleii.com/spiix/monolith"}]}),component:Monolith});
const chapters=monolithChapters;
function Monolith(){
  const [access,setAccess]=useState(false),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState(""); const navigate=useNavigate();
  useEffect(()=>{if(hasMonolithAccess())setAccess(true);else void navigate({to:"/spiix/signal",replace:true});},[navigate]);
  if(!access)return <main className="spiix-page-head"><div className="spiix-wrap"><p className="spiix-kicker">CHECKING DOCUMENT ACCESS</p></div></main>;
  return <main className="sx-monolith"><header className="sx-monolith-cover"><div className="spiix-wrap"><p className="spiix-kicker">GROWTH LADDERS MONOLITH / SPIIX OPERATING GUIDE</p><h1 className="sx-mark-reveal">The<br/>Monolith.</h1><div className="sx-cover-rule"><span>STEVE PEELE II</span><span>14+ YEARS / $350M+ ANNUAL PIPELINE EXPOSURE</span></div><p>Monolith is the whole body of work.<br/>Get the Signal is the framework. The OS is its mechanism. Signal is the defined measure.</p><div className="sx-actions sx-document-actions" data-pdf-exclude><Button className="spiix-button" disabled={exporting} onClick={async()=>{const documentRoot=document.querySelector<HTMLElement>(".sx-monolith");if(!documentRoot)return;setExporting(true);setExportError("");try{const {downloadMonolithPdf}=await import("@/lib/spiix-pdf");await downloadMonolithPdf(documentRoot);}catch{setExportError("The PDF could not be created. Use the print-ready copy below to save as PDF.");}finally{setExporting(false);}}}><Download/>{exporting?"PREPARING DOCUMENT…":"DOWNLOAD THE PDF"}</Button><Button variant="ghost" className="spiix-button spiix-button-outline" onClick={()=>window.print()}><Printer/>PRINT-READY COPY</Button></div>{exportError&&<p className="sx-intake-error" role="alert">{exportError}</p>}<p>This is the SPIIX operating guide within Monolith. Growth Ladders — Operators Edition carries the companion book, playbooks, and diagnostic.</p><div className="sx-actions" data-pdf-exclude><Link to="/growth-ladders" className="spiix-text-link">Explore Growth Ladders <ArrowUpRight/></Link></div><div className="sx-cover-diagram" aria-label="Growth operating loop">{["SIGNAL","STRATEGY","SYSTEMS","SCALE"].map((word,i)=><div key={word}><span>0{i+1}</span><strong>{word}</strong><small>{["READ","CHOOSE","BUILD","COMPOUND"][i]}</small></div>)}</div></div></header><div className="spiix-wrap sx-document-layout"><aside className="sx-document-toc"><p className="spiix-kicker">CONTENTS / 01—08</p><nav aria-label="Monolith chapters">{chapters.map((chapter,index)=><a key={chapter} href={`#chapter-${index+1}`}><span>{["I","II","III","IV","V","VI","VII","VIII"][index]}</span>{chapter}</a>)}</nav><Link to="/spiix" className="spiix-text-link">← SPIIX home</Link></aside><div className="sx-document-body">
  <Chapter n={1} title={chapters[0]}><p className="sx-document-lead">Growth is a system, not a campaign.</p><p>Acquisition creates an opening. Positioning makes it relevant. Conversion captures intent. Qualification tests fit. Sales turns accepted demand into revenue. Retention determines what that revenue is worth. Break a handoff and the entire system pays for it.</p><p>SPIIX connects those decisions. The work starts with the commercial constraint—not a channel plan, a tool purchase, or a calendar. The point is to improve the system’s useful output, not to make every department look busy.</p><figure className="sx-revenue-chain"><figcaption>FIG.00 / THE COMMERCIAL CHAIN</figcaption>{["Acquisition","Message match","Conversion","Qualification","Opportunity","Revenue","Retention","Learning"].map((word,i)=><div key={word}><span>0{i+1}</span>{word}<ArrowUpRight/></div>)}</figure><p>These frameworks draw on 14+ years across SaaS, startups, and global marketing operations, including $350M+ in annual pipeline exposure at NTT DATA/Nexient. The frameworks are operating tools. The calculations below are explicit scenarios, not claims about a client’s results.</p></Chapter>
  <Chapter n={2} title={chapters[1]}><p>The OS mechanises Get the Signal through owners, workflows, tools, and review cadence. The layers describe what must be true. They are not departments. Each layer depends on the one below it, and every result returns to Signal.</p><OsDeepDive/><p>Order matters because it reduces the cost of being wrong. Validate the evidence before making a choice. Bound the choice before building. Prove the workflow before expanding. When the market changes, return to the layer where the assumption stopped holding.</p></Chapter>
  <Chapter n={3} title={chapters[2]}><p>The blueprint describes how the work moves. Audit reads Signal. Strategy selects the intervention. Build installs Systems. Scale tests durability and creates the next audit.</p><BlueprintDeepDive/><FrameworkTable caption="PHASE × LAYER / WHAT EACH PASS CHANGES" headings={["Phase","Primary layer","Decision at the end"]} rows={[["Audit","Signal","Which constraint limits useful growth?"],["Strategy","Strategy","Which intervention earns the next commitment?"],["Build","Systems","Can the workflow run and be measured end to end?"],["Scale","Scale → Signal","Should we expand, revise, or stop?"]]}/></Chapter>
  <Chapter n={4} title={chapters[3]}><p className="sx-document-lead">Velocity has units. Use them.</p><div className="sx-equation"><span>EXPECTED WON VALUE / DAY</span><strong>(Opportunities × Deal value × Win rate) ÷ Cycle days</strong><p>(100 × $20,000 × 25%) ÷ 60 days = <b>$8,333 / day</b></p></div><p>This is a snapshot estimate, not cash collected. The opportunity cohort, average deal size, win-rate definition, and cycle window must match. Do not substitute all open pipeline for qualified opportunities, or attributed revenue for actual won value.</p><FrameworkTable caption="ONE-LEVER SENSITIVITY / HYPOTHETICAL COHORT, OTHER INPUTS HELD CONSTANT" headings={["Scenario","Input change","Expected won value / day","Lift"]} rows={[["Baseline","100 opportunities · $20,000 · 25% · 60 days","$8,333","0%"],["Better qualification","Win rate 25% → 30%","$10,000","20%"],["Faster cycle","60 → 50 days","$10,000","20%"],["Higher deal value","$20,000 → $24,000","$10,000","20%"]]}/><p>Use the model to locate leverage, then inspect the trade-off. A shorter cycle that discounts margin is not a free win. More opportunities that lower win rate can reduce useful velocity. Pair the primary measure with cost, quality, and capacity guardrails.</p><VelocityModeler/><h3 className="sx-document-subhead">Conversion economics.</h3><p>Relative lift and percentage-point lift are different. At a 2% baseline conversion rate, a 20% relative lift produces 2.4%, not 22%. At constant traffic and customer value, revenue rises by the same relative amount. The instrument below holds acquisition, retention, and customer value constant.</p><ImpactEngine/></Chapter>
  <Chapter n={5} title={chapters[4]}><p>Signal is a defined measure: a reading with an agreed definition, unit, cohort, time window, and decision attached. Get the Signal is the framework that uses it. Noise can be accurate and still be useless. A traffic report is not wrong; it is insufficient when the decision is whether to fund accepted pipeline.</p><SignalDeepDive/><p>Do not force certainty from incomplete data. Check the definition, sample, delay, and competing explanation. If the evidence cannot distinguish two plausible causes, the next action is a diagnostic test—not a confident allocation.</p></Chapter>
  <Chapter n={6} title={chapters[5]}><p>The framework stays the same. The engagement changes the depth of diagnosis, the operating cadence, or the transfer of judgment.</p><FrameworkTable caption="ENGAGEMENT ARCHITECTURE / CHOOSE THE OPERATING NEED" headings={["Model","Need","Work product","Boundary"]} rows={[["The Lens / GTM Audit","Name and prioritize the constraint","A fixed-scope diagnostic and ranked action plan","A diagnostic is not an implementation team."],["The Engine / Fractional Advisory","Keep commercial decisions and execution aligned","Decision reviews, sequencing, operating accountability","Scope and cadence are agreed before work begins."],["The Catalyst / Mentorship","Build the leader’s judgment","1:1 decision work, context, and pressure-testing","Leadership development is not outsourced execution."]]}/><div className="sx-actions"><Button asChild variant="ghost" className="spiix-button spiix-button-outline"><Link to="/spiix/compare">Compare engagements</Link></Button><Button asChild className="spiix-button"><Link to="/spiix/signal">GET THE SIGNAL</Link></Button><Link to="/spiix/connect" className="spiix-text-link">Start the conversation →</Link></div></Chapter>
  <Chapter n={7} title={chapters[6]}><OperatorPrinciples/></Chapter>
  <Chapter n={8} title={chapters[7]}><FrameworkTable caption="WORKING DEFINITIONS / AGREE ON THE LANGUAGE BEFORE THE NUMBER" headings={["Term","Definition"]} rows={glossary}/><p className="sx-document-lead">The goal is not to do more marketing.<br/>The goal is to make marketing matter.</p><Link to="/spiix/connect" className="spiix-text-link">Bring the hard problem. Start the conversation →</Link></Chapter>
  </div></div></main>;
}
function Chapter({n,title,children}:{n:number;title?:string;children:React.ReactNode}){return <section id={`chapter-${n}`} className="sx-document-chapter"><p className="spiix-kicker">CHAPTER {String(n).padStart(2,"0")} / SPIIX</p><h2>{title}</h2>{children}<MonolithDepth chapter={n}/></section>;}