import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SpiixPageHead } from "@/components/spiix-page";
import { signalRequestSchema, unlockMonolith } from "@/lib/spiix-access";

export const Route = createFileRoute("/spiix/get-the-signal")({
  head: () => ({ meta: [{ title: "Get the Signal — Unlock the Monolith | SPIIX" }, { name: "description", content: "Access the complete SPIIX operating manual: architecture, blueprint, velocity models, signal frameworks, and operator principles." }, { property: "og:title", content: "Get the Signal — SPIIX" }, { property: "og:description", content: "Four details. Instant access to the Monolith." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }], links: [{ rel: "canonical", href: "https://stevepeeleii.com/spiix/get-the-signal" }] }),
  component: SignalRequest,
});
function SignalRequest() {
  const navigate = useNavigate();
  const [data,setData] = useState({ name: "", email: "", company: "", role: "" });
  const [errors,setErrors] = useState<Record<string,string>>({});
  const [storageError,setStorageError] = useState("");
  return <main><SpiixPageHead code="SIGNAL ACCESS / THE MONOLITH" title="Get the signal." copy="The complete SPIIX operating manual. Frameworks, decisions, and instruments for building a growth system that works."/><section className="spiix-section sx-intake-section"><div className="spiix-wrap sx-gate-layout"><div><p className="spiix-kicker">DOCUMENT 01 / EIGHT CHAPTERS</p><h2 className="sx-heading">The Monolith.</h2><p className="sx-section-narrative">The thesis. The OS. The blueprint. Pipeline velocity. Signal discipline. Engagement models. Operator principles. A working glossary.</p><div className="sx-document-stamp"><FileText/><span>STRATEGIC OPERATING MANUAL<br/>STEVE PEELE II / SPIIX</span></div></div><form className="sx-intake-panel sx-clip" noValidate onSubmit={event => { event.preventDefault(); const parsed=signalRequestSchema.safeParse(data); if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(issue=>[String(issue.path[0]),issue.message])));return;} setErrors({}); if(!unlockMonolith()){setStorageError("Allow browser storage to save your access, then try again.");return;} void navigate({to:"/spiix/monolith"}); }}><p className="spiix-kicker">REQUEST ACCESS / INSTANT UNLOCK</p><div className="sx-intake-fields">{(["name","email","company","role"] as const).map(key => <div className="spiix-field" key={key}><label htmlFor={`signal-${key}`}>{key}</label><input id={`signal-${key}`} value={data[key]} type={key==="email"?"email":"text"} autoComplete={key==="email"?"email":key==="name"?"name":key==="company"?"organization":"organization-title"} required maxLength={key==="email"?254:key==="company"?120:100} aria-invalid={Boolean(errors[key])} aria-describedby={errors[key]?`signal-error-${key}`:undefined} onChange={e=>setData({...data,[key]:e.target.value})}/>{errors[key]&&<p id={`signal-error-${key}`} className="sx-intake-error">{errors[key]}</p>}</div>)}</div>{storageError&&<p role="alert" className="sx-intake-error">{storageError}</p>}<Button type="submit" className="spiix-button">GET THE SIGNAL <ArrowRight/></Button><p className="sx-footnote">Instant access on this browser. These details are not sent or saved; only an access flag is stored. No mailing-list enrollment.</p><Link to="/spiix/connect" className="spiix-text-link">Start a conversation instead →</Link></form></div></section></main>;
}