import { createFileRoute, Link } from "@tanstack/react-router";
import { SpiixPageHead } from "@/components/spiix-page";
import { SpiixSectionLabel } from "@/components/spiix-blueprint";
import { Button } from "@/components/ui/button";
import { OsDeepDive, BlueprintDeepDive, OperatorPrinciples, FrameworkTable } from "@/components/spiix-frameworks";

export const Route = createFileRoute("/spiix/os")({ head: () => ({ meta: [{ title: "The SPIIX Operating System — Audit, Strategy, Build, Scale" }, { name: "description", content: "The four-layer SPIIX operating system for finding growth constraints and building repeatable revenue machinery." }, { property: "og:title", content: "The SPIIX Operating System" }, { property: "og:description", content: "Audit, Strategy, Build, and Scale—four connected layers for durable growth." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }], links: [{ rel: "canonical", href: "https://stevepeeleii.com/spiix/os" }] }), component: OsPage });

function OsPage(){return <main><SpiixPageHead code="SYSTEM FILE 00 / STRATEGIC OPERATING SYSTEM" title="Build in the right order." copy="Signal establishes the truth. Strategy makes the choice. Systems execute it. Scale earns the next investment."/><section className="spiix-section"><div className="spiix-wrap"><SpiixSectionLabel number="01">ARCHITECTURE / FOUR DEPENDENT LAYERS</SpiixSectionLabel><h2 className="sx-heading">Nothing scales above a broken foundation.</h2><p className="sx-section-narrative">The OS is a sequence of dependencies, not a collection of tactics. Read the commercial constraint first. Choose the intervention second. Install the workflow third. Increase volume only when the result and its economics hold.</p><OsDeepDive/></div></section><section className="spiix-section"><div className="spiix-wrap"><SpiixSectionLabel number="02">EXECUTION / THE FOUR-PHASE BLUEPRINT</SpiixSectionLabel><h2 className="sx-heading">The layers are the architecture.<br/>The phases are the work.</h2><p className="sx-section-narrative">Audit, Strategy, Build, and Scale move through the same dependencies. Each phase leaves an artifact and an explicit exit condition. A meeting is not an exit condition. A working, readable result is.</p><BlueprintDeepDive/></div></section><section className="spiix-section"><div className="spiix-wrap"><SpiixSectionLabel number="03">OPERATING CADENCE / KEEP THE LOOP CLOSED</SpiixSectionLabel><h2 className="sx-heading">Every result becomes new signal.</h2><FrameworkTable caption="DECISION CADENCE / ADAPT THE WINDOW TO THE SALES MOTION" headings={["Review","Readings","Decision"]} rows={[["Weekly execution","Launches, routing failures, response time, data gaps","Unblock the workflow. Do not mistake an early reading for a mature result."],["Monthly commercial","Cohorts, accepted pipeline, stage progression, cost, capacity","Expand, revise, or stop the intervention."],["Quarterly system","Segment economics, retention, dependencies, changing constraints","Re-audit the system and reset priorities."]]}/><p className="sx-section-narrative">One owner records the evidence, decision, and next action. Sales and marketing use the same stage definitions. Reviews produce choices—not another dashboard. If a result stops repeating, return to the layer where the assumption broke.</p></div></section><section className="spiix-section"><div className="spiix-wrap"><SpiixSectionLabel number="04">OPERATOR PRINCIPLES</SpiixSectionLabel><h2 className="sx-heading">Rules that survive the tooling.</h2><OperatorPrinciples/><div className="sx-actions"><Button asChild className="spiix-button"><Link to="/spiix/signal">GET THE SIGNAL</Link></Button><Button asChild variant="ghost" className="spiix-button spiix-button-outline"><Link to="/spiix/signals">Read the signal framework</Link></Button></div></div></section></main>}
