import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { useEffect, useState } from "react";
import heroImage from "@/assets/spiix/spiix-hero.jpg";
import girdersImage from "@/assets/spiix/spiix-girders.jpg";
import { spiixOriginal } from "@/data/spiix-reference";
import { SpiixGuidance } from "@/components/spiix-guidance";
import { SpiixBlueprint, SpiixSectionLabel } from "@/components/spiix-blueprint";
import { PipelineChart, VelocityModeler } from "@/components/spiix-impact-tools";
import { Button } from "@/components/ui/button";
import { featuredRecommendations, profile } from "@/data/resume";

export const Route = createFileRoute("/spiix/")({
 head:()=>({meta:[{title:"SPIIX — Strategic Operating System"},{name:"description",content:"SPIIX is Steve Peele II’s strategic operating system for founders and operators. Signal, strategy, execution, and scale."},{property:"og:title",content:"SPIIX — Strategic Operating System"},{property:"og:description",content:"Strategy is potential. Execution is kinetic. Signal turns the first into the second."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"https://stevepeeleii.com/spiix"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"ProfessionalService",name:"SPIIX",url:"https://stevepeeleii.com/spiix",founder:{"@type":"Person",name:"Steve Peele II"}})}]}),component:SpiixHome,
});
const clients=spiixOriginal.fm.map(item=>({category:item.tag,name:item.name,stat:item.metric,role:item.role}));
const bars=[{name:"Inman",value:70},{name:"Astronomer",value:60},{name:"API Nation",value:50},{name:"Percy",value:50},{name:"EBTH",value:50}];
function SpiixHome(){
 const [live,setLive]=useState(331.0);
 useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const timer=window.setInterval(()=>setLive(v=>v+.037),1100);return()=>window.clearInterval(timer);},[]);
 return <main>
  <section id="monolith" className="spiix-hero"><img src={heroImage} alt="Brutalist tower against a dark sky" width={1920} height={1088}/><div className="sx-hero-grid"/><div className="sx-grain"/><div className="spiix-wrap"><div className="spiix-hero-content"><p className="spiix-kicker sx-rise-1">/ STRATEGIC OPERATING SYSTEM · CINCINNATI · OH · AVAILABLE · EST. PAN LABS CONSULTING</p><div className="sx-hero-main"><div><div className="sx-mark-stage"><h1 className="sx-mark-reveal">SPIIX</h1></div><h2 className="sx-rise-1">Strategy is potential. <span>Execution is kinetic. Signal turns the first into the second.</span></h2><p className="spiix-lede sx-rise-2">14+ years across SaaS, startups, and global marketing operations. $350M+ in annual pipeline exposure. Senior judgment for the growth system you need to build.</p><div className="sx-actions sx-rise-3"><Button asChild className="spiix-button"><Link to="/spiix/signal">GET THE SIGNAL <ArrowRight/></Link></Button><Button asChild variant="ghost" className="spiix-button spiix-button-outline"><a href="#blueprint">How I build <ArrowRight/></a></Button></div></div><div className="sx-live-panel sx-clip sx-rise-4"><p className="spiix-kicker">/ LIVE — SIGNAL PULSE</p><strong>{live.toFixed(3)}</strong><p>Illustrative activity counter · not a result</p></div></div><div className="sx-hero-stats sx-rise-5">{[["14+","Years scaling SaaS & tech"],["$350M+","Pipeline revenue driven"],["10M+","Clients, sign-ups & users served"],["55%","Pipeline velocity increase"],["4","Startup exits contributed to"]].map(([value,label])=><div key={value}><strong>{value}</strong><span>{label}</span></div>)}</div></div></div></section>
  <section className="spiix-section"><div className="spiix-wrap sx-practice"><p className="spiix-kicker">/ THE PRACTICE</p><h2>Pan Labs is where I do the work.<br/><span>SPIIX is where I teach it.</span></h2><p>Pan Labs delivers the work. SPIIX transfers the judgment: how to read the constraint, choose the next move, and build the system behind it. For founders, marketing leaders, and operators who need decisions—not another course.</p><div className="sx-audience">{spiixOriginal.vm.map(item=><p key={item}><span>▸</span>{item}</p>)}</div></div></section>
  <SpiixBlueprint/>
  <section className="spiix-section sx-ledger"><div className="spiix-wrap"><SpiixSectionLabel number="02">THE VELOCITY LEDGER / PIPELINE & ADOPTION VELOCITY</SpiixSectionLabel><h2 className="sx-heading">Velocity, measured.<br/>Not claimed.</h2><div className="sx-ledger-grid"><div className="sx-chart-panel"><p className="sx-chart-label">FIG.01 / CUMULATIVE PIPELINE · 2012—2025</p><PipelineChart/></div><div className="sx-chart-panel"><p className="sx-chart-label">FIG.02 / VELOCITY BY ENGAGEMENT</p><div className="sx-bars">{bars.map(bar=><div className="sx-bar" key={bar.name}><div><span>{bar.name}</span><span>+{bar.value}%</span></div><div className="sx-bar-track"><i style={{width:`${bar.value}%`}}/></div></div>)}</div><div className="sx-dotloop"><span>DOTLOOP / USER GROWTH</span><strong>400%+</strong></div></div></div><div className="sx-mini-stats">{[["+30%","Conversion rate lift"],["−20%","Cost per acquisition"],["−25%","Churn, cut before exit"],["+45%","Program ROI"]].map(([n,label])=><div key={n}><strong>{n}</strong><span>{label}</span></div>)}</div><VelocityModeler/></div></section>
  <section className="spiix-section"><div className="spiix-wrap"><SpiixSectionLabel>WHO I HELP / THE WALL OF TROPHIES</SpiixSectionLabel><h2 className="sx-heading">Real pipeline. Real revenue.<br/>Real exits.</h2><div className="sx-client-grid">{clients.map(client=><article className="sx-client-card" key={client.name}><p>{client.category}</p><h3>{client.name}</h3>{client.stat&&<strong>{client.stat}</strong>}<span>{client.role}</span></article>)}</div><p className="sx-logo-label">LOGOS / COMPANIES I'VE SERVED — GREYSCALE, HOVER FOR KINETIC</p><div className="sx-letter-grid">{clients.map(client=><div title={client.name} className="sx-letter-tile" key={client.name}>{client.name.split(/[ /]/).map(word=>word[0]).join("").slice(0,3)}</div>)}</div><div className="sx-marquee"><p>WORKED ALONGSIDE</p><div className="sx-marquee-track">{[0,1].map(copy=><div className="sx-marquee-group" aria-hidden={copy>0?true:undefined} key={copy}>{["Twilio","Intercom","HubSpot","Minute Suites","Hoist Hydration"].map(name=><span key={name}>{name}</span>)}</div>)}</div></div></div></section>
  <section className="spiix-section sx-testimonial-section"><img className="sx-testimonial-bg" src={girdersImage} width={1536} height={1024} alt="" loading="lazy"/><div className="spiix-wrap"><SpiixSectionLabel number="03">WHAT LEADERS SAY / LINKEDIN</SpiixSectionLabel><div className="sx-testimonial-grid">{featuredRecommendations.map(item=><article key={item.name}><span className="sx-quote-mark">“</span><blockquote>{item.quote}</blockquote><h3>{item.name}</h3><p>{item.title}</p></article>)}</div><div className="sx-intake-strip"><div><p className="spiix-kicker">/ THE MONOLITH — INSTANT ACCESS</p><h3>The complete operating manual.</h3></div><Button asChild className="spiix-button"><Link to="/spiix/signal">GET THE SIGNAL <ArrowRight/></Link></Button></div></div></section>
  <section className="spiix-section"><div className="spiix-wrap"><SpiixSectionLabel number="04">ENGAGE / THE GTM TERMINAL</SpiixSectionLabel><h2 className="sx-heading">Three ways in.<br/>One filter for qualified work.</h2><div className="sx-engage-grid">{spiixOriginal.gm.map((item,i)=><article className={`sx-engage-card sx-clip ${i===1?"is-featured":""}`} key={item.slug}><p className="spiix-kicker">{item.code} / {item.name}</p><h3>{["The Lens","The Engine","The Catalyst"][i]}</h3><p>{item.summary}</p><dl><div><dt>AVAILABILITY</dt><dd>{item.availability}</dd></div><div><dt>PRIMARY KPI</dt><dd>{item.kpi}</dd></div></dl><Button asChild className={`spiix-button ${i===1?"":"spiix-button-outline"}`}><Link to="/spiix/signal">GET THE SIGNAL <ArrowRight/></Link></Button></article>)}</div><p className="sx-qualifier">Not sure which fits? <Link to="/spiix/signal">GET THE SIGNAL</Link> for the framework. Start a conversation when you need it installed.</p></div></section>
  <SpiixGuidance/>
  <section className="spiix-section"><div className="spiix-wrap sx-direct-line"><SpiixSectionLabel>DIRECT LINE</SpiixSectionLabel><h2>Bring the hard problem.</h2><div className="sx-contact-row"><a href={`mailto:${profile.email}`}>{profile.email}</a><a href={`tel:${profile.phone.replace(/\./g,"")}`}>{profile.phone}</a><span>CINCINNATI · OH</span></div><div className="sx-actions"><Button asChild className="spiix-button"><Link to="/spiix/signal">GET THE SIGNAL <ArrowRight/></Link></Button><Button asChild variant="ghost" className="spiix-button spiix-button-outline"><a href={profile.booking} target="_blank" rel="noreferrer">Request a conversation <ArrowRight/></a></Button></div></div></section>
 </main>;
}
