import { useId, useState, type CSSProperties } from "react";
import { impactScenario, velocityScenario } from "@/lib/spiix-models";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Calculator } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

export const formatMoney = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
export function SpiixSlider({ label, value, onChange, min = 0, max = 100, step = 1, display, unit = "%" }: { label: string; value: number; onChange: (n: number) => void; min?: number; max?: number; step?: number; display?: string; unit?: "%" | "USD/month" }) {
  const id = useId();
  const scale=(n:number)=>unit==="%"?`${n}%`:`${formatMoney(n)}/mo`;
  return <div className="sx-slider"><div><label htmlFor={id}>{label}</label><output htmlFor={id}>{display ?? `${value}%`}</output></div><input id={id} aria-label={label} aria-valuetext={display ?? `${value}%`} type="range" min={min} max={max} step={step} value={value} style={{ "--slider-fill": `${(value - min) / (max - min) * 100}%` } as CSSProperties} onChange={e => {const n=Number(e.target.value);if(Number.isFinite(n))onChange(Math.min(max,Math.max(min,n)));}} /><div className="sx-slider-scale"><span>{scale(min)}</span><span>{scale(max)}</span></div></div>;
}
export function PipelineChart({ multiplier = 1, projection = false, values: customValues, labels: customLabels, maxValue: customMax, axis = "money" }: { multiplier?: number; projection?: boolean; values?: number[]; labels?: string[]; maxValue?: number; axis?: "money" | "percent" }) {
 const id=useId().replace(/:/g,"");
 const values=customValues??[0,14,38,71,112,158,205,244,279,307,326,341,348,352];
 const max=customMax??360;
 const labels=customLabels??(projection?["M1","M6","M12","M18","M24"]:["2012","2015","2018","2021","2025"]);
 const points=values.map((value,index)=>`${60+index/(values.length-1)*660},${260-value*multiplier/max*220}`).join(" ");
  return <svg className="sx-pipeline-chart" viewBox="0 0 760 310" role="img" aria-label={projection?"Modeled scenario over time":"Cumulative pipeline from 2012 to 2025"}><defs><linearGradient id={id} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="var(--sx-kinetic)" stopOpacity=".24"/><stop offset="100%" stopColor="var(--sx-kinetic)" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4].map(index=><g key={index}><line x1="60" y1={260-index*55} x2="720" y2={260-index*55} className="sx-chart-grid"/><text x="52" y={264-index*55} textAnchor="end">{axis==="percent"?`${index*max/4}%`:max<1?`$${Math.round(index*max/4*1000)}K`:`$${Number((index*max/4).toFixed(1))}M`}</text></g>)}<polygon points={`60,260 ${points} 720,260`} fill={`url(#${id})`}/><polyline className="sx-chart-line" points={points} pathLength="1"/>{labels.map((label,index)=><text key={label} x={60+index/(labels.length-1)*660} y="292" textAnchor="middle">{label}</text>)}</svg>;
}
export function VelocityModeler(){
 const [velocity,setVelocity]=useState(20),[adoption,setAdoption]=useState(80);
 const model=velocityScenario(velocity,adoption);
 return <div className="sx-modeler sx-instrument sx-clip"><div className="sx-modeler-title"><p className="spiix-kicker">FIG.03 / VELOCITY MODELER</p><span className="sx-live">● LIVE / 12 MONTHS</span></div><h3>Measure the adoption effect.</h3><p className="sx-instrument-caption">Read the 12-month pipeline total against a $24M baseline; adoption determines how much of the target lift is realized.</p><div className="sx-modeler-grid"><div><SpiixSlider label="Target pipeline velocity lift" value={velocity} onChange={setVelocity} max={100}/><SpiixSlider label="Adoption target at month 12" value={adoption} onChange={setAdoption}/><dl className="sx-instrument-assumptions"><div><dt>BASE PIPELINE</dt><dd>$2,000,000 / month</dd></div><div><dt>ADOPTION RAMP</dt><dd>Linear · 0% → {adoption}% · 12 months</dd></div><div><dt>MONTHLY MODEL</dt><dd>Base × (1 + lift × adoption)</dd></div></dl></div><div className="sx-model-charts"><div><p className="sx-chart-label">CUMULATIVE PIPELINE / USD</p><strong>{formatMoney(model.total)}</strong><PipelineChart projection values={model.cumulative.map(n=>n/1_000_000)} maxValue={50} labels={["M0","M3","M6","M9","M12"]}/></div><div><p className="sx-chart-label">ADOPTION / % OF WORKFLOW</p><strong>{adoption}% at M12</strong><PipelineChart projection values={model.adoptionValues} maxValue={100} axis="percent" labels={["M0","M3","M6","M9","M12"]}/></div></div></div><div className="sx-model-totals"><div><span>12-MONTH INCREMENTAL PIPELINE / USD</span><strong>{formatMoney(model.uplift)}</strong></div><div><span>REALIZED LIFT AT MONTH 12 / RELATIVE %</span><strong>{(velocity*adoption/100).toFixed(1)}%</strong></div></div><p className="sx-footnote">Scenario, not a forecast. Pipeline is opportunity value, not booked revenue. Base volume and opportunity quality are held constant.</p></div>;
}
export function ImpactEngine(){
 const [revenue,setRevenue]=useState(100000),[lift,setLift]=useState(20),[horizon,setHorizon]=useState(12);
 const model=impactScenario(revenue,lift,horizon);
 return <div className="sx-impact-engine sx-instrument"><p className="sx-instrument-caption">Read the monthly revenue curve above a constant baseline; the total sums incremental revenue over months 1–24.</p><SpiixSlider label="Baseline monthly revenue / USD" value={revenue} onChange={setRevenue} min={10000} max={500000} step={10000} unit="USD/month" display={`${formatMoney(revenue)} / mo`}/><div className="sx-segment-field"><p>CONVERSION LIFT / RELATIVE %</p><div role="group" aria-label="Conversion lift">{[5,10,20,30].map(n=><Button key={n} variant="ghost" className="sx-segment" aria-pressed={lift===n} onClick={()=>setLift(n)}>+{n}%</Button>)}</div></div><div className="sx-segment-field"><p>TIME TO FULL LIFT / MONTHS</p><div role="group" aria-label="Time to full lift">{[{n:3,label:"3 MO"},{n:6,label:"6 MO"},{n:12,label:"12 MO"}].map(({n,label})=><Button key={n} variant="ghost" className="sx-segment" aria-pressed={horizon===n} onClick={()=>setHorizon(n)}>{label}</Button>)}</div></div><p className="sx-chart-label">MONTHLY REVENUE / USD · 24-MONTH WINDOW</p><PipelineChart projection values={model.monthly.map(n=>n/1_000_000)} maxValue={Math.ceil(model.final/100000)*.1} labels={["M0","M6","M12","M18","M24"]}/><div className="sx-model-totals"><div><span>24-MONTH INCREMENTAL REVENUE / USD</span><strong>{formatMoney(model.incremental)}</strong></div><div><span>REVENUE AT MONTH 24 / USD PER MONTH</span><strong>{formatMoney(model.final)} / mo</strong></div></div><p className="sx-footnote">Monthly revenue = baseline × (1 + relative lift × ramp). Linear ramp reaches full lift at month {horizon}, then holds. Traffic, customer value, retention, and costs remain constant. Scenario, not a revenue guarantee.</p></div>;
}
export function FloatingImpactCalc() {
  return <Dialog><DialogTrigger asChild><Button className="sx-floating-calc spiix-button spiix-button-outline"><Calculator /> OS IMPACT CALC</Button></DialogTrigger><DialogContent className="spiix sx-impact-dialog"><p className="spiix-kicker">/ OS IMPACT CALCULATOR</p><DialogTitle>Conversion economics.</DialogTitle><DialogDescription>Set the baseline, relative lift, and ramp. Read the 24-month effect in USD.</DialogDescription><ImpactEngine /><div className="sx-actions"><Button asChild variant="ghost" className="spiix-button spiix-button-outline"><Link to="/spiix/impact">Full engine <ArrowRight /></Link></Button><Button asChild className="spiix-button"><Link to="/spiix/get-the-signal">GET THE SIGNAL <ArrowRight /></Link></Button></div></DialogContent></Dialog>;
}
