import { FrameworkTable } from "./spiix-frameworks";
import { operatingCases } from "@/data/spiix-operating-cases";

function Flow({ caption, steps }: { caption: string; steps: string[] }) {
  return <figure className="sx-operator-flow"><figcaption>{caption}</figcaption><div>{steps.map((step,i)=><div key={step}><span>0{i+1}</span><strong>{step}</strong></div>)}</div></figure>;
}
export function OperatingCases({ index }: { index: 0 | 1 }) {
  const item=operatingCases[index];
  return <article className="sx-document-depth"><p className="spiix-kicker">WORKED SCENARIO / NOT A CLIENT RESULT</p><h2 className="sx-heading">{item.title}</h2><p>{item.context}</p><div className="sx-worked-example"><h3>What the signal said.</h3><p>{item.reading}</p><h3>What changed in the system.</h3><p>{item.intervention}</p></div><FrameworkTable caption={index===0?"FIG.05 / BEFORE → AFTER · ILLUSTRATIVE COHORTS":"FIG.05 / CONTROL A → VARIANT B · ILLUSTRATIVE COHORTS"} headings={["Reading",index===0?"Before":"Control A",index===0?"After":"Variant B"]} rows={item.rows}/><h3 className="sx-document-subhead">Read the outcome. Keep the boundary.</h3><p>{item.outcome}</p><p>{item.limitation}</p></article>;
}
export function OperatingDepth({ kind }: { kind: "os" | "signals" }) {
  return <div className="sx-document-depth">{kind==="os"?<>
    <h2 className="sx-heading">Dependencies are operating contracts.</h2><p>The architecture fails when its outputs are optional. Each layer owes the next layer a usable artifact, a named owner, and a readiness decision. A strategy deck is not a system. A live automation is not evidence that the strategy was right.</p>
    <Flow caption="FIG.03 / DEPENDENCY CONTRACTS · THE OUTPUT BECOMES THE NEXT INPUT" steps={["Signal / cohort + constraint", "Strategy / choice + stop rule", "Systems / owner + workflow", "Scale / economics + capacity"]}/>
    <FrameworkTable caption="RETURN PATH / REPAIR THE LOWEST BROKEN DEPENDENCY" headings={["Observed break","Return to","Repair before proceeding"]} rows={[["Reports disagree about qualified pipeline","Signal","Reconcile stage definitions, sources, and cohort maturity."],["Teams launch conflicting experiments","Strategy","Rank the constraint and publish the decision not to pursue the alternatives."],["Correct message, missed handoffs","Systems","Fix ownership, routing, and response-time alerts before buying more demand."],["More pipeline, slower progression","Scale","Read sales capacity and cohort economics; reduce volume if service quality breaks."]]}/>
    <h3 className="sx-document-subhead">A cadence is a decision schedule.</h3><p>Daily checks protect the workflow. Weekly reviews remove execution blockers. Monthly reviews judge matured cohorts. Quarterly reviews revisit segment economics and the constraint itself. Do not ask a weekly meeting to prove a six-month sales-cycle hypothesis.</p>
    <FrameworkTable caption="DECISION RIGHTS / WHO CAN CHANGE WHAT" headings={["Window","Accountable owner","Required artifact","Decision"]} rows={[["Daily exceptions","Workflow owner","Failed handoffs + age of queue","Repair or escalate."],["Weekly delivery","Growth operator","Experiment register + blockers","Keep, resequence, or unblock work."],["Monthly commercial","Revenue owner with sales + marketing","Mature cohort + cost + capacity","Expand, revise, or stop allocation."],["Quarterly system","Executive sponsor","Constraint map + unit economics","Change priorities and resource boundaries."]]}/>
    <p>Every review ends with an owner, an action, a date, and a reading that could overturn the decision. If nothing can change the decision, the meeting is reporting—not operating.</p>
  </>:<>
    <h2 className="sx-heading">A signal needs a denominator and a clock.</h2><p>“Pipeline is up” leaves four questions unanswered: compared with what, from which buyers, over which window, and at what cost? Read counts and rates together. Segment the cohort before interpreting the average. Preserve unknowns instead of hiding them in a total.</p>
    <Flow caption="FIG.03 / EVIDENCE CHAIN · NO SINGLE STAGE PROVES THE WHOLE" steps={["Source / buyer + intent","Lead / response + fit","Opportunity / acceptance + value","Won / margin + payback","Retention / realized value"]}/>
    <FrameworkTable caption="FAILURE MAP / WHEN THE READING MISLEADS" headings={["Pattern","False conclusion","Better reading"]} rows={[["Lead rate rises, acceptance falls","The page converts better.","Accepted opportunities per visitor and per dollar, by segment."],["Recent cohort has fewer wins","The new campaign failed.","Compare equivalent ages and track stage progression while wins mature."],["Pipeline value jumps after a definition change","Demand improved.","Restate the baseline under the same definition."],["Low response coverage","The buyer is unqualified.","Audit routing and contact attempts before labeling intent."],["Revenue rises, margin falls","Scale worked.","Contribution margin, payback, retention, and delivery capacity."]]}/>
    <h3 className="sx-document-subhead">Choose the action before you decorate the chart.</h3><p>Leading indicators are useful for diagnosis. Lagging indicators establish realized value. Neither works alone: an early signal without a downstream check invites local optimization; waiting for revenue alone makes the operating loop too slow.</p>
    <FrameworkTable caption="DECISION CADENCE / MATCH THE CLAIM TO THE MATURITY" headings={["Readout","Evidence","Permitted action"]} rows={[["Daily instrument check","Coverage, routing, data freshness","Repair collection. No performance verdict."],["Weekly diagnostic","Message response, rejection reasons, response time","Revise a hypothesis or remove workflow friction."],["Mature cohort review","Acceptance, progression, cost, comparable segments","Allocate within pre-agreed limits."],["Economic review","Won margin, payback, retention","Earn or withdraw the right to scale."]]}/>
    <p>Use a written decision brief: observation, alternative explanations, intervention, primary reading, guardrails, owner, review date, and stop rule. A failed experiment with a clear readout is useful. An apparently successful experiment with no decision boundary is expensive noise.</p>
  </>}</div>;
}