/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CvRouteImport } from './routes/cv'
import { Route as DemandCurveAnalysisRouteImport } from './routes/demand-curve-analysis'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as FractionalGrowthAdvisoryRouteImport } from './routes/fractional-growth-advisory'
import { Route as GrowthLaddersRouteImport } from './routes/growth-ladders'
import { Route as MusicRouteImport } from './routes/music'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SpiixRouteImport } from './routes/spiix'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesGtmAuditRouteImport } from './routes/services.gtm-audit'
import { Route as ServicesLogisticsRouteImport } from './routes/services.logistics'
import { Route as ServicesWebsiteBuildRouteImport } from './routes/services.website-build'
import { Route as SpiixIndexRouteImport } from './routes/spiix.index'
import { Route as SpiixCompareRouteImport } from './routes/spiix.compare'
import { Route as SpiixConnectRouteImport } from './routes/spiix.connect'
import { Route as SpiixDiagnosticsRouteImport } from './routes/spiix.diagnostics'
import { Route as SpiixGetTheSignalRouteImport } from './routes/spiix.get-the-signal'
import { Route as SpiixImpactRouteImport } from './routes/spiix.impact'
import { Route as SpiixMonolithRouteImport } from './routes/spiix.monolith'
import { Route as SpiixOsRouteImport } from './routes/spiix.os'
import { Route as SpiixSignalRouteImport } from './routes/spiix.signal'
import { Route as SpiixSignalReportRouteImport } from './routes/spiix.signal-report'
import { Route as SpiixSignalsRouteImport } from './routes/spiix.signals'
import { Route as SpiixWhoIHelpRouteImport } from './routes/spiix.who-i-help'
import { Route as SpiixEngageEliteMentorshipRouteImport } from './routes/spiix.engage.elite-mentorship'
import { Route as SpiixEngageFractionalAdvisoryRouteImport } from './routes/spiix.engage.fractional-advisory'
import { Route as SpiixEngageGtmAuditRouteImport } from './routes/spiix.engage.gtm-audit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandCurveAnalysisRoute = DemandCurveAnalysisRouteImport.update({
  id: '/demand-curve-analysis',
  path: '/demand-curve-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const FractionalGrowthAdvisoryRoute =
  FractionalGrowthAdvisoryRouteImport.update({
    id: '/fractional-growth-advisory',
    path: '/fractional-growth-advisory',
    getParentRoute: () => rootRouteImport,
  } as any)
const GrowthLaddersRoute = GrowthLaddersRouteImport.update({
  id: '/growth-ladders',
  path: '/growth-ladders',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiixRoute = SpiixRouteImport.update({
  id: '/spiix',
  path: '/spiix',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGtmAuditRoute = ServicesGtmAuditRouteImport.update({
  id: '/gtm-audit',
  path: '/gtm-audit',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLogisticsRoute = ServicesLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebsiteBuildRoute = ServicesWebsiteBuildRouteImport.update({
  id: '/website-build',
  path: '/website-build',
  getParentRoute: () => ServicesRoute,
} as any)
const SpiixIndexRoute = SpiixIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixCompareRoute = SpiixCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixConnectRoute = SpiixConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixDiagnosticsRoute = SpiixDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixGetTheSignalRoute = SpiixGetTheSignalRouteImport.update({
  id: '/get-the-signal',
  path: '/get-the-signal',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixImpactRoute = SpiixImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixMonolithRoute = SpiixMonolithRouteImport.update({
  id: '/monolith',
  path: '/monolith',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixOsRoute = SpiixOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixSignalRoute = SpiixSignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixSignalReportRoute = SpiixSignalReportRouteImport.update({
  id: '/signal-report',
  path: '/signal-report',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixSignalsRoute = SpiixSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixWhoIHelpRoute = SpiixWhoIHelpRouteImport.update({
  id: '/who-i-help',
  path: '/who-i-help',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixEngageEliteMentorshipRoute =
  SpiixEngageEliteMentorshipRouteImport.update({
    id: '/engage/elite-mentorship',
    path: '/engage/elite-mentorship',
    getParentRoute: () => SpiixRoute,
  } as any)
const SpiixEngageFractionalAdvisoryRoute =
  SpiixEngageFractionalAdvisoryRouteImport.update({
    id: '/engage/fractional-advisory',
    path: '/engage/fractional-advisory',
    getParentRoute: () => SpiixRoute,
  } as any)
const SpiixEngageGtmAuditRoute = SpiixEngageGtmAuditRouteImport.update({
  id: '/engage/gtm-audit',
  path: '/engage/gtm-audit',
  getParentRoute: () => SpiixRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/demand-curve-analysis': typeof DemandCurveAnalysisRoute
  '/experience': typeof ExperienceRoute
  '/fractional-growth-advisory': typeof FractionalGrowthAdvisoryRoute
  '/growth-ladders': typeof GrowthLaddersRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/recommendations': typeof RecommendationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/spiix': typeof SpiixRouteWithChildren
  '/work': typeof WorkRoute
  '/services/gtm-audit': typeof ServicesGtmAuditRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/website-build': typeof ServicesWebsiteBuildRoute
  '/spiix/compare': typeof SpiixCompareRoute
  '/spiix/connect': typeof SpiixConnectRoute
  '/spiix/diagnostics': typeof SpiixDiagnosticsRoute
  '/spiix/get-the-signal': typeof SpiixGetTheSignalRoute
  '/spiix/impact': typeof SpiixImpactRoute
  '/spiix/monolith': typeof SpiixMonolithRoute
  '/spiix/os': typeof SpiixOsRoute
  '/spiix/signal': typeof SpiixSignalRoute
  '/spiix/signal-report': typeof SpiixSignalReportRoute
  '/spiix/signals': typeof SpiixSignalsRoute
  '/spiix/who-i-help': typeof SpiixWhoIHelpRoute
  '/services/': typeof ServicesIndexRoute
  '/spiix/': typeof SpiixIndexRoute
  '/spiix/engage/elite-mentorship': typeof SpiixEngageEliteMentorshipRoute
  '/spiix/engage/fractional-advisory': typeof SpiixEngageFractionalAdvisoryRoute
  '/spiix/engage/gtm-audit': typeof SpiixEngageGtmAuditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/demand-curve-analysis': typeof DemandCurveAnalysisRoute
  '/experience': typeof ExperienceRoute
  '/fractional-growth-advisory': typeof FractionalGrowthAdvisoryRoute
  '/growth-ladders': typeof GrowthLaddersRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/recommendations': typeof RecommendationsRoute
  '/work': typeof WorkRoute
  '/services/gtm-audit': typeof ServicesGtmAuditRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/website-build': typeof ServicesWebsiteBuildRoute
  '/spiix/compare': typeof SpiixCompareRoute
  '/spiix/connect': typeof SpiixConnectRoute
  '/spiix/diagnostics': typeof SpiixDiagnosticsRoute
  '/spiix/get-the-signal': typeof SpiixGetTheSignalRoute
  '/spiix/impact': typeof SpiixImpactRoute
  '/spiix/monolith': typeof SpiixMonolithRoute
  '/spiix/os': typeof SpiixOsRoute
  '/spiix/signal': typeof SpiixSignalRoute
  '/spiix/signal-report': typeof SpiixSignalReportRoute
  '/spiix/signals': typeof SpiixSignalsRoute
  '/spiix/who-i-help': typeof SpiixWhoIHelpRoute
  '/services': typeof ServicesIndexRoute
  '/spiix': typeof SpiixIndexRoute
  '/spiix/engage/elite-mentorship': typeof SpiixEngageEliteMentorshipRoute
  '/spiix/engage/fractional-advisory': typeof SpiixEngageFractionalAdvisoryRoute
  '/spiix/engage/gtm-audit': typeof SpiixEngageGtmAuditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/demand-curve-analysis': typeof DemandCurveAnalysisRoute
  '/experience': typeof ExperienceRoute
  '/fractional-growth-advisory': typeof FractionalGrowthAdvisoryRoute
  '/growth-ladders': typeof GrowthLaddersRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/recommendations': typeof RecommendationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/spiix': typeof SpiixRouteWithChildren
  '/work': typeof WorkRoute
  '/services/gtm-audit': typeof ServicesGtmAuditRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/website-build': typeof ServicesWebsiteBuildRoute
  '/spiix/compare': typeof SpiixCompareRoute
  '/spiix/connect': typeof SpiixConnectRoute
  '/spiix/diagnostics': typeof SpiixDiagnosticsRoute
  '/spiix/get-the-signal': typeof SpiixGetTheSignalRoute
  '/spiix/impact': typeof SpiixImpactRoute
  '/spiix/monolith': typeof SpiixMonolithRoute
  '/spiix/os': typeof SpiixOsRoute
  '/spiix/signal': typeof SpiixSignalRoute
  '/spiix/signal-report': typeof SpiixSignalReportRoute
  '/spiix/signals': typeof SpiixSignalsRoute
  '/spiix/who-i-help': typeof SpiixWhoIHelpRoute
  '/services/': typeof ServicesIndexRoute
  '/spiix/': typeof SpiixIndexRoute
  '/spiix/engage/elite-mentorship': typeof SpiixEngageEliteMentorshipRoute
  '/spiix/engage/fractional-advisory': typeof SpiixEngageFractionalAdvisoryRoute
  '/spiix/engage/gtm-audit': typeof SpiixEngageGtmAuditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/cv'
    | '/demand-curve-analysis'
    | '/experience'
    | '/fractional-growth-advisory'
    | '/growth-ladders'
    | '/music'
    | '/portfolio'
    | '/recommendations'
    | '/services'
    | '/spiix'
    | '/work'
    | '/services/gtm-audit'
    | '/services/logistics'
    | '/services/website-build'
    | '/spiix/compare'
    | '/spiix/connect'
    | '/spiix/diagnostics'
    | '/spiix/get-the-signal'
    | '/spiix/impact'
    | '/spiix/monolith'
    | '/spiix/os'
    | '/spiix/signal'
    | '/spiix/signal-report'
    | '/spiix/signals'
    | '/spiix/who-i-help'
    | '/services/'
    | '/spiix/'
    | '/spiix/engage/elite-mentorship'
    | '/spiix/engage/fractional-advisory'
    | '/spiix/engage/gtm-audit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/cv'
    | '/demand-curve-analysis'
    | '/experience'
    | '/fractional-growth-advisory'
    | '/growth-ladders'
    | '/music'
    | '/portfolio'
    | '/recommendations'
    | '/work'
    | '/services/gtm-audit'
    | '/services/logistics'
    | '/services/website-build'
    | '/spiix/compare'
    | '/spiix/connect'
    | '/spiix/diagnostics'
    | '/spiix/get-the-signal'
    | '/spiix/impact'
    | '/spiix/monolith'
    | '/spiix/os'
    | '/spiix/signal'
    | '/spiix/signal-report'
    | '/spiix/signals'
    | '/spiix/who-i-help'
    | '/services'
    | '/spiix'
    | '/spiix/engage/elite-mentorship'
    | '/spiix/engage/fractional-advisory'
    | '/spiix/engage/gtm-audit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/cv'
    | '/demand-curve-analysis'
    | '/experience'
    | '/fractional-growth-advisory'
    | '/growth-ladders'
    | '/music'
    | '/portfolio'
    | '/recommendations'
    | '/services'
    | '/spiix'
    | '/work'
    | '/services/gtm-audit'
    | '/services/logistics'
    | '/services/website-build'
    | '/spiix/compare'
    | '/spiix/connect'
    | '/spiix/diagnostics'
    | '/spiix/get-the-signal'
    | '/spiix/impact'
    | '/spiix/monolith'
    | '/spiix/os'
    | '/spiix/signal'
    | '/spiix/signal-report'
    | '/spiix/signals'
    | '/spiix/who-i-help'
    | '/services/'
    | '/spiix/'
    | '/spiix/engage/elite-mentorship'
    | '/spiix/engage/fractional-advisory'
    | '/spiix/engage/gtm-audit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ContactRoute: typeof ContactRoute
  CvRoute: typeof CvRoute
  DemandCurveAnalysisRoute: typeof DemandCurveAnalysisRoute
  ExperienceRoute: typeof ExperienceRoute
  FractionalGrowthAdvisoryRoute: typeof FractionalGrowthAdvisoryRoute
  GrowthLaddersRoute: typeof GrowthLaddersRoute
  MusicRoute: typeof MusicRoute
  PortfolioRoute: typeof PortfolioRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SpiixRoute: typeof SpiixRouteWithChildren
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand-curve-analysis': {
      id: '/demand-curve-analysis'
      path: '/demand-curve-analysis'
      fullPath: '/demand-curve-analysis'
      preLoaderRoute: typeof DemandCurveAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fractional-growth-advisory': {
      id: '/fractional-growth-advisory'
      path: '/fractional-growth-advisory'
      fullPath: '/fractional-growth-advisory'
      preLoaderRoute: typeof FractionalGrowthAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-ladders': {
      id: '/growth-ladders'
      path: '/growth-ladders'
      fullPath: '/growth-ladders'
      preLoaderRoute: typeof GrowthLaddersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spiix': {
      id: '/spiix'
      path: '/spiix'
      fullPath: '/spiix'
      preLoaderRoute: typeof SpiixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/gtm-audit': {
      id: '/services/gtm-audit'
      path: '/gtm-audit'
      fullPath: '/services/gtm-audit'
      preLoaderRoute: typeof ServicesGtmAuditRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/logistics': {
      id: '/services/logistics'
      path: '/logistics'
      fullPath: '/services/logistics'
      preLoaderRoute: typeof ServicesLogisticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/website-build': {
      id: '/services/website-build'
      path: '/website-build'
      fullPath: '/services/website-build'
      preLoaderRoute: typeof ServicesWebsiteBuildRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/spiix/': {
      id: '/spiix/'
      path: '/'
      fullPath: '/spiix/'
      preLoaderRoute: typeof SpiixIndexRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/compare': {
      id: '/spiix/compare'
      path: '/compare'
      fullPath: '/spiix/compare'
      preLoaderRoute: typeof SpiixCompareRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/connect': {
      id: '/spiix/connect'
      path: '/connect'
      fullPath: '/spiix/connect'
      preLoaderRoute: typeof SpiixConnectRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/diagnostics': {
      id: '/spiix/diagnostics'
      path: '/diagnostics'
      fullPath: '/spiix/diagnostics'
      preLoaderRoute: typeof SpiixDiagnosticsRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/get-the-signal': {
      id: '/spiix/get-the-signal'
      path: '/get-the-signal'
      fullPath: '/spiix/get-the-signal'
      preLoaderRoute: typeof SpiixGetTheSignalRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/impact': {
      id: '/spiix/impact'
      path: '/impact'
      fullPath: '/spiix/impact'
      preLoaderRoute: typeof SpiixImpactRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/monolith': {
      id: '/spiix/monolith'
      path: '/monolith'
      fullPath: '/spiix/monolith'
      preLoaderRoute: typeof SpiixMonolithRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/os': {
      id: '/spiix/os'
      path: '/os'
      fullPath: '/spiix/os'
      preLoaderRoute: typeof SpiixOsRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/signal': {
      id: '/spiix/signal'
      path: '/signal'
      fullPath: '/spiix/signal'
      preLoaderRoute: typeof SpiixSignalRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/signal-report': {
      id: '/spiix/signal-report'
      path: '/signal-report'
      fullPath: '/spiix/signal-report'
      preLoaderRoute: typeof SpiixSignalReportRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/signals': {
      id: '/spiix/signals'
      path: '/signals'
      fullPath: '/spiix/signals'
      preLoaderRoute: typeof SpiixSignalsRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/who-i-help': {
      id: '/spiix/who-i-help'
      path: '/who-i-help'
      fullPath: '/spiix/who-i-help'
      preLoaderRoute: typeof SpiixWhoIHelpRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/engage/elite-mentorship': {
      id: '/spiix/engage/elite-mentorship'
      path: '/engage/elite-mentorship'
      fullPath: '/spiix/engage/elite-mentorship'
      preLoaderRoute: typeof SpiixEngageEliteMentorshipRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/engage/fractional-advisory': {
      id: '/spiix/engage/fractional-advisory'
      path: '/engage/fractional-advisory'
      fullPath: '/spiix/engage/fractional-advisory'
      preLoaderRoute: typeof SpiixEngageFractionalAdvisoryRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/engage/gtm-audit': {
      id: '/spiix/engage/gtm-audit'
      path: '/engage/gtm-audit'
      fullPath: '/spiix/engage/gtm-audit'
      preLoaderRoute: typeof SpiixEngageGtmAuditRouteImport
      parentRoute: typeof SpiixRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesGtmAuditRoute: typeof ServicesGtmAuditRoute
  ServicesLogisticsRoute: typeof ServicesLogisticsRoute
  ServicesWebsiteBuildRoute: typeof ServicesWebsiteBuildRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesGtmAuditRoute: ServicesGtmAuditRoute,
  ServicesLogisticsRoute: ServicesLogisticsRoute,
  ServicesWebsiteBuildRoute: ServicesWebsiteBuildRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SpiixRouteChildren {
  SpiixCompareRoute: typeof SpiixCompareRoute
  SpiixConnectRoute: typeof SpiixConnectRoute
  SpiixDiagnosticsRoute: typeof SpiixDiagnosticsRoute
  SpiixGetTheSignalRoute: typeof SpiixGetTheSignalRoute
  SpiixImpactRoute: typeof SpiixImpactRoute
  SpiixMonolithRoute: typeof SpiixMonolithRoute
  SpiixOsRoute: typeof SpiixOsRoute
  SpiixSignalRoute: typeof SpiixSignalRoute
  SpiixSignalReportRoute: typeof SpiixSignalReportRoute
  SpiixSignalsRoute: typeof SpiixSignalsRoute
  SpiixWhoIHelpRoute: typeof SpiixWhoIHelpRoute
  SpiixIndexRoute: typeof SpiixIndexRoute
  SpiixEngageEliteMentorshipRoute: typeof SpiixEngageEliteMentorshipRoute
  SpiixEngageFractionalAdvisoryRoute: typeof SpiixEngageFractionalAdvisoryRoute
  SpiixEngageGtmAuditRoute: typeof SpiixEngageGtmAuditRoute
}

const SpiixRouteChildren: SpiixRouteChildren = {
  SpiixCompareRoute: SpiixCompareRoute,
  SpiixConnectRoute: SpiixConnectRoute,
  SpiixDiagnosticsRoute: SpiixDiagnosticsRoute,
  SpiixGetTheSignalRoute: SpiixGetTheSignalRoute,
  SpiixImpactRoute: SpiixImpactRoute,
  SpiixMonolithRoute: SpiixMonolithRoute,
  SpiixOsRoute: SpiixOsRoute,
  SpiixSignalRoute: SpiixSignalRoute,
  SpiixSignalReportRoute: SpiixSignalReportRoute,
  SpiixSignalsRoute: SpiixSignalsRoute,
  SpiixWhoIHelpRoute: SpiixWhoIHelpRoute,
  SpiixIndexRoute: SpiixIndexRoute,
  SpiixEngageEliteMentorshipRoute: SpiixEngageEliteMentorshipRoute,
  SpiixEngageFractionalAdvisoryRoute: SpiixEngageFractionalAdvisoryRoute,
  SpiixEngageGtmAuditRoute: SpiixEngageGtmAuditRoute,
}

const SpiixRouteWithChildren = SpiixRoute._addFileChildren(SpiixRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  ContactRoute: ContactRoute,
  CvRoute: CvRoute,
  DemandCurveAnalysisRoute: DemandCurveAnalysisRoute,
  ExperienceRoute: ExperienceRoute,
  FractionalGrowthAdvisoryRoute: FractionalGrowthAdvisoryRoute,
  GrowthLaddersRoute: GrowthLaddersRoute,
  MusicRoute: MusicRoute,
  PortfolioRoute: PortfolioRoute,
  RecommendationsRoute: RecommendationsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SpiixRoute: SpiixRouteWithChildren,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
