/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CvRouteImport } from './routes/cv'
import { Route as DemandCurveAnalysisRouteImport } from './routes/demand-curve-analysis'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as MusicRouteImport } from './routes/music'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SpiixRouteImport } from './routes/spiix'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesGtmAuditRouteImport } from './routes/services.gtm-audit'
import { Route as ServicesLogisticsRouteImport } from './routes/services.logistics'
import { Route as ServicesWebsiteBuildRouteImport } from './routes/services.website-build'
import { Route as SpiixIndexRouteImport } from './routes/spiix.index'
import { Route as SpiixCompareRouteImport } from './routes/spiix.compare'
import { Route as SpiixConnectRouteImport } from './routes/spiix.connect'
import { Route as SpiixImpactRouteImport } from './routes/spiix.impact'
import { Route as SpiixOsRouteImport } from './routes/spiix.os'
import { Route as SpiixSignalsRouteImport } from './routes/spiix.signals'
import { Route as SpiixWhoIHelpRouteImport } from './routes/spiix.who-i-help'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandCurveAnalysisRoute = DemandCurveAnalysisRouteImport.update({
  id: '/demand-curve-analysis',
  path: '/demand-curve-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiixRoute = SpiixRouteImport.update({
  id: '/spiix',
  path: '/spiix',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGtmAuditRoute = ServicesGtmAuditRouteImport.update({
  id: '/gtm-audit',
  path: '/gtm-audit',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLogisticsRoute = ServicesLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebsiteBuildRoute = ServicesWebsiteBuildRouteImport.update({
  id: '/website-build',
  path: '/website-build',
  getParentRoute: () => ServicesRoute,
} as any)
const SpiixIndexRoute = SpiixIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixCompareRoute = SpiixCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixConnectRoute = SpiixConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixImpactRoute = SpiixImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixOsRoute = SpiixOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixSignalsRoute = SpiixSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => SpiixRoute,
} as any)
const SpiixWhoIHelpRoute = SpiixWhoIHelpRouteImport.update({
  id: '/who-i-help',
  path: '/who-i-help',
  getParentRoute: () => SpiixRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/demand-curve-analysis': typeof DemandCurveAnalysisRoute
  '/experience': typeof ExperienceRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/recommendations': typeof RecommendationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/spiix': typeof SpiixRouteWithChildren
  '/work': typeof WorkRoute
  '/services/gtm-audit': typeof ServicesGtmAuditRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/website-build': typeof ServicesWebsiteBuildRoute
  '/spiix/compare': typeof SpiixCompareRoute
  '/spiix/connect': typeof SpiixConnectRoute
  '/spiix/impact': typeof SpiixImpactRoute
  '/spiix/os': typeof SpiixOsRoute
  '/spiix/signals': typeof SpiixSignalsRoute
  '/spiix/who-i-help': typeof SpiixWhoIHelpRoute
  '/services/': typeof ServicesIndexRoute
  '/spiix/': typeof SpiixIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/demand-curve-analysis': typeof DemandCurveAnalysisRoute
  '/experience': typeof ExperienceRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/recommendations': typeof RecommendationsRoute
  '/work': typeof WorkRoute
  '/services/gtm-audit': typeof ServicesGtmAuditRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/website-build': typeof ServicesWebsiteBuildRoute
  '/spiix/compare': typeof SpiixCompareRoute
  '/spiix/connect': typeof SpiixConnectRoute
  '/spiix/impact': typeof SpiixImpactRoute
  '/spiix/os': typeof SpiixOsRoute
  '/spiix/signals': typeof SpiixSignalsRoute
  '/spiix/who-i-help': typeof SpiixWhoIHelpRoute
  '/services': typeof ServicesIndexRoute
  '/spiix': typeof SpiixIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/cv': typeof CvRoute
  '/demand-curve-analysis': typeof DemandCurveAnalysisRoute
  '/experience': typeof ExperienceRoute
  '/music': typeof MusicRoute
  '/portfolio': typeof PortfolioRoute
  '/recommendations': typeof RecommendationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/spiix': typeof SpiixRouteWithChildren
  '/work': typeof WorkRoute
  '/services/gtm-audit': typeof ServicesGtmAuditRoute
  '/services/logistics': typeof ServicesLogisticsRoute
  '/services/website-build': typeof ServicesWebsiteBuildRoute
  '/spiix/compare': typeof SpiixCompareRoute
  '/spiix/connect': typeof SpiixConnectRoute
  '/spiix/impact': typeof SpiixImpactRoute
  '/spiix/os': typeof SpiixOsRoute
  '/spiix/signals': typeof SpiixSignalsRoute
  '/spiix/who-i-help': typeof SpiixWhoIHelpRoute
  '/services/': typeof ServicesIndexRoute
  '/spiix/': typeof SpiixIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/cv'
    | '/demand-curve-analysis'
    | '/experience'
    | '/music'
    | '/portfolio'
    | '/recommendations'
    | '/services'
    | '/spiix'
    | '/work'
    | '/services/gtm-audit'
    | '/services/logistics'
    | '/services/website-build'
    | '/spiix/compare'
    | '/spiix/connect'
    | '/spiix/impact'
    | '/spiix/os'
    | '/spiix/signals'
    | '/spiix/who-i-help'
    | '/services/'
    | '/spiix/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/cv'
    | '/demand-curve-analysis'
    | '/experience'
    | '/music'
    | '/portfolio'
    | '/recommendations'
    | '/work'
    | '/services/gtm-audit'
    | '/services/logistics'
    | '/services/website-build'
    | '/spiix/compare'
    | '/spiix/connect'
    | '/spiix/impact'
    | '/spiix/os'
    | '/spiix/signals'
    | '/spiix/who-i-help'
    | '/services'
    | '/spiix'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/contact'
    | '/cv'
    | '/demand-curve-analysis'
    | '/experience'
    | '/music'
    | '/portfolio'
    | '/recommendations'
    | '/services'
    | '/spiix'
    | '/work'
    | '/services/gtm-audit'
    | '/services/logistics'
    | '/services/website-build'
    | '/spiix/compare'
    | '/spiix/connect'
    | '/spiix/impact'
    | '/spiix/os'
    | '/spiix/signals'
    | '/spiix/who-i-help'
    | '/services/'
    | '/spiix/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ContactRoute: typeof ContactRoute
  CvRoute: typeof CvRoute
  DemandCurveAnalysisRoute: typeof DemandCurveAnalysisRoute
  ExperienceRoute: typeof ExperienceRoute
  MusicRoute: typeof MusicRoute
  PortfolioRoute: typeof PortfolioRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SpiixRoute: typeof SpiixRouteWithChildren
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand-curve-analysis': {
      id: '/demand-curve-analysis'
      path: '/demand-curve-analysis'
      fullPath: '/demand-curve-analysis'
      preLoaderRoute: typeof DemandCurveAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spiix': {
      id: '/spiix'
      path: '/spiix'
      fullPath: '/spiix'
      preLoaderRoute: typeof SpiixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/gtm-audit': {
      id: '/services/gtm-audit'
      path: '/gtm-audit'
      fullPath: '/services/gtm-audit'
      preLoaderRoute: typeof ServicesGtmAuditRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/logistics': {
      id: '/services/logistics'
      path: '/logistics'
      fullPath: '/services/logistics'
      preLoaderRoute: typeof ServicesLogisticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/website-build': {
      id: '/services/website-build'
      path: '/website-build'
      fullPath: '/services/website-build'
      preLoaderRoute: typeof ServicesWebsiteBuildRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/spiix/': {
      id: '/spiix/'
      path: '/'
      fullPath: '/spiix/'
      preLoaderRoute: typeof SpiixIndexRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/compare': {
      id: '/spiix/compare'
      path: '/compare'
      fullPath: '/spiix/compare'
      preLoaderRoute: typeof SpiixCompareRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/connect': {
      id: '/spiix/connect'
      path: '/connect'
      fullPath: '/spiix/connect'
      preLoaderRoute: typeof SpiixConnectRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/impact': {
      id: '/spiix/impact'
      path: '/impact'
      fullPath: '/spiix/impact'
      preLoaderRoute: typeof SpiixImpactRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/os': {
      id: '/spiix/os'
      path: '/os'
      fullPath: '/spiix/os'
      preLoaderRoute: typeof SpiixOsRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/signals': {
      id: '/spiix/signals'
      path: '/signals'
      fullPath: '/spiix/signals'
      preLoaderRoute: typeof SpiixSignalsRouteImport
      parentRoute: typeof SpiixRoute
    }
    '/spiix/who-i-help': {
      id: '/spiix/who-i-help'
      path: '/who-i-help'
      fullPath: '/spiix/who-i-help'
      preLoaderRoute: typeof SpiixWhoIHelpRouteImport
      parentRoute: typeof SpiixRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesGtmAuditRoute: typeof ServicesGtmAuditRoute
  ServicesLogisticsRoute: typeof ServicesLogisticsRoute
  ServicesWebsiteBuildRoute: typeof ServicesWebsiteBuildRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesGtmAuditRoute: ServicesGtmAuditRoute,
  ServicesLogisticsRoute: ServicesLogisticsRoute,
  ServicesWebsiteBuildRoute: ServicesWebsiteBuildRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SpiixRouteChildren {
  SpiixCompareRoute: typeof SpiixCompareRoute
  SpiixConnectRoute: typeof SpiixConnectRoute
  SpiixImpactRoute: typeof SpiixImpactRoute
  SpiixOsRoute: typeof SpiixOsRoute
  SpiixSignalsRoute: typeof SpiixSignalsRoute
  SpiixWhoIHelpRoute: typeof SpiixWhoIHelpRoute
  SpiixIndexRoute: typeof SpiixIndexRoute
}

const SpiixRouteChildren: SpiixRouteChildren = {
  SpiixCompareRoute: SpiixCompareRoute,
  SpiixConnectRoute: SpiixConnectRoute,
  SpiixImpactRoute: SpiixImpactRoute,
  SpiixOsRoute: SpiixOsRoute,
  SpiixSignalsRoute: SpiixSignalsRoute,
  SpiixWhoIHelpRoute: SpiixWhoIHelpRoute,
  SpiixIndexRoute: SpiixIndexRoute,
}

const SpiixRouteWithChildren = SpiixRoute._addFileChildren(SpiixRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  ContactRoute: ContactRoute,
  CvRoute: CvRoute,
  DemandCurveAnalysisRoute: DemandCurveAnalysisRoute,
  ExperienceRoute: ExperienceRoute,
  MusicRoute: MusicRoute,
  PortfolioRoute: PortfolioRoute,
  RecommendationsRoute: RecommendationsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SpiixRoute: SpiixRouteWithChildren,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
